mentoring_manager/mentoring_manager/urls.py
# Mentoring Manager is a web application to manage mentoring sessions between mentors and entrepreneurs.
# Copyright (C) 2013  Alvaro Hurtado Mochon (alvarohurtado84@gmail.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

# ADMIN
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Home
    url(r'^$', 'mentoring_manager.views.home', name='home'),

    # People access (Profiles)
    url(r'^profile/', include('people.urls')),

    # Mentors
    url(r'^mentors/', include('mentors.urls')),

    # Entrepreneurs
    url(r'^entrepreneurs/', include('entrepreneurs.urls')),
    
    # Mentoring sessions
    url(r'^sessions/', include('mentoring_sessions.urls')),

    # ADMIN
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    
    # ACCOUNTS
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', name='logout'),
    
    # TOS
    url(
        r'^rules/$',
        TemplateView.as_view(template_name='rules.html'),
        name = 'rules',
        ),

    # MANIFESTO
    url(
        r'^manifesto/$',
        TemplateView.as_view(template_name='manifesto.html'),
        name = 'manifesto',
        ),
)

mentoring_manager/people/urls.py
# Mentoring Manager is a web application to manage mentoring sessions between mentors and entrepreneurs.
# Copyright (C) 2013  Alvaro Hurtado Mochon (alvarohurtado84@gmail.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    
    # Modify or update the user profile
    url(r'edit/$', 'people.views.edit', name="person_edit"),
    
    # Profile of any user
    url(r'(?P<username>[a-zA-Z0-9\-\_]+)/$', 'people.views.profile', name="person_profile"),
    
    # Profile of the logged user
    url(r'$', 'people.views.person_home', name="person_home"),
    
)

mentoring_manager/people/models.py
# Mentoring Manager is a web application to manage mentoring sessions between mentors and entrepreneurs.
# Copyright (C) 2013  Alvaro Hurtado Mochon (alvarohurtado84@gmail.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
from django.db import models

from django.contrib.auth.models import User

#from entrepreneurs.models import Entrepreneur
#from mentor.models import Mentor

class Person(models.Model):
    """Contains the data of a Person."""
    
    user = models.OneToOneField(User)
    
    avatar = models.ImageField(upload_to="avatars/people")
    # bio
    description = models.TextField()
    
    country = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    
    twitter_user = models.CharField(max_length=50, blank=True)
    linkedin_profile = models.URLField(blank=True)
    # others social profiles
    others_social_profiles = models.TextField(blank=True)
    
    # why are you here? what are you looking for, interests, who can you help
    # background / aptitudes
    why = models.TextField()
    
    # Languages
    english = models.BooleanField(blank=True)
    spanish = models.BooleanField(blank=True)
    others_languages = models.CharField(max_length=100, blank=True)
    
    def is_mentor(self):
        """Check if this Person is a mentor."""
        try:
            self.mentor
            return True
        except:
            return False
    
    is_mentor.boolean = True
    
    
    def is_entrepreneur(self):
        """Check if this Person is an entrepreneur."""
        try:
            self.entrepreneur
            return True
        except:
            return False
    
    is_entrepreneur.boolean = True

mentoring_manager/people/forms.py
# Mentoring Manager is a web application to manage mentoring sessions between mentors and entrepreneurs.
# Copyright (C) 2013  Alvaro Hurtado Mochon (alvarohurtado84@gmail.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.forms import ModelForm

from people.models import Person
from django.contrib.auth.models import User

class PersonForm(ModelForm):
    class Meta:
        model = Person
        exclude = ["user"]
        
class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password']
        
    def save(self, force_insert=False, force_update=False, commit=True):
        m = super(UserForm, self).save(commit=False)
        
        m.set_password(self.cleaned_data["password"])
        if commit:
            m.save()
        
        return m

mentoring_manager/people/views.py
# Mentoring Manager is a web application to manage mentoring sessions between mentors and entrepreneurs.
# Copyright (C) 2013  Alvaro Hurtado Mochon (alvarohurtado84@gmail.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# Create your views here.

from django.utils.translation import ugettext as _
from django.shortcuts import render_to_response
from django.shortcuts import get_object_or_404

from django.http import Http404
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator
from django.core.urlresolvers import reverse
from django.template import RequestContext

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from mentors.models import Mentor
from people.models import Person

from mentors.forms import MentorForm
from people.forms import UserForm
from people.forms import PersonForm

@login_required
def edit(request):
    user = request.user
    msg = None
    
    if request.method == "POST":
        form = PersonForm(request.POST, request.FILES, instance=user.person)
        if form.is_valid():
            form.save()
            
            msg = _("Your data have been save.")
        else:
            msg = _("Sorry, something went wrong.")
            
    else:
        form = PersonForm(instance=user.person)
        
    return render_to_response("person/edit.html",
                {
                "msg": msg,
                "form": form,
                },
                context_instance=RequestContext(request)
            )

def profile(request, username):
    user = get_object_or_404(User, username=username)
    person = user.person
    
    if person.is_mentor() and person.is_entrepreneur():
        return render_to_response("person/profile.html",
                    {
                    "person": person,
                    },
                    context_instance=RequestContext(request)
                )
    
    elif person.is_mentor():
        return HttpResponseRedirect(
            reverse("mentors_profile", args=[user.username,]))
    
    elif person.is_entrepreneur():
        return HttpResponseRedirect(
            reverse("entrepreneurs_profile", args=[user.username,]))
    
    else:
        raise Http404

@login_required
def person_home(request):
    user = request.user
    
    if user.person.is_mentor() and user.person.is_entrepreneur():
        return render_to_response("person/home.html",
                    {
                    "person": user.person,
                    },
                    context_instance=RequestContext(request)
                )
    
    elif user.person.is_mentor():
        return HttpResponseRedirect(
            reverse("mentors_profile", args=[user.username,]))
    
    elif user.person.is_entrepreneur():
        return HttpResponseRedirect(
            reverse("entrepreneurs_profile", args=[user.username,]))
    
    else:
        raise Http404
    
    

mentoring_manager/templates/person/edit.html
{% extends "base.html" %}


{% block body-class %}class="portfolio1"{% endblock %}

{% block content %}


    <div class="container">
        <h1 class="onleft light">Edit profile</h1>
        {% if not user.person.is_entrepreneur %}
            <a href="{% url "entrepreneurs_create" %}" class="btn large shaded onright margin-top">Do you have an startup?</a>
        {% endif %}
        {% if not user.person.is_mentor %}
          <a href="{% url "mentors_create" %}" class="btn large shaded onright margin-top">Do you want to be a mentor?</a>
        {% endif %}

        <div class="row clear">
            <div class="span8">
                {% if msg %}
                    <p class="error">{{ msg }}</p>
                {% endif %}
                
                <form action="{% url "person_edit" %}" method="post" enctype='multipart/form-data' class="cols2">   
                    {% csrf_token %}
                        {% comment %}
                            <!--<p>
                                                    {{ form.avatar.label_tag }}
                                                    {{ form.avatar }}
                                                </p>
                                                {% if form.errors %}
                                            {{ form.errors }}
                                        {% endif %}
                                                <hr>-->
                        {% endcomment %}
                    
                        <p>
                            <label for="id_description">Biography:</label> 
                            <textarea cols="40" id="id_description" name="description" rows="10" required="required" placeholder="Include some information about your background, etc.">{{form.description.value}}</textarea>
                            {% include "form_errors.html" with errors=form.description.errors %}
                        </p>
                        <p>
                            <label for="id_why">Which are your motivations:</label> 
                            <textarea cols="40" id="id_why" name="why" rows="10" required="required">{{form.why.value}}</textarea>
                            {% include "form_errors.html" with errors=form.why.errors %}
                        </p>
                        <p>
                            <label for="id_country">Country:</label> 
                            <input id="id_country" maxlength="100" name="country" type="text" value="{{form.country.value}}" required="required"/>
                            {% include "form_errors.html" with errors=form.country.errors %}
                        </p>
                        <p>
                            <label for="id_city">City:</label> 
                            <input id="id_city" maxlength="100" name="city" type="text" value="{{form.city.value}}" required="required"/>
                            {% include "form_errors.html" with errors=form.description.errors %}
                        </p>
                        <p>
                            <label for="id_avatar">Avatar:</label> 
                            <input id="id_avatar" name="avatar" type="file"/>
                            {% include "form_errors.html" with errors=form.avatar.errors %}
                        </p>
                        <h2 class="clear light">
                            Social accounts
                        </h2>
                        <p>
                            <label for="id_twitter_user">Twitter user:</label> 
                            <input id="id_twitter_user" maxlength="50" name="twitter_user" type="text" value="{{form.twitter_user.value}}"/>
                            {% include "form_errors.html" with errors=form.description.errors %}
                        </p>
                        <p>
                            <label for="id_linkedin_profile">Linkedin profile:</label> 
                            <input id="id_linkedin_profile" maxlength="200" name="linkedin_profile" type="text" value="{{form.linkedin_profile.value}}"/>
                            {% include "form_errors.html" with errors=form.description.errors %}
                        </p>
                        <p>
                            <label for="id_others_social_profiles">Others social profiles:</label> 
                            <textarea cols="40" id="id_others_social_profiles" name="others_social_profiles" rows="10">{{form.others_social_profiles.value}}</textarea>
                            {% include "form_errors.html" with errors=form.description.errors %}
                        </p>
                        <h2 class="clear light">Spoken languages: </h2>
                        <p>
                            <label for="id_english">English:</label> <input id="id_english" name="english" type="checkbox" checked="{{form.english.value}}"/>
                            <label for="id_spanish">Spanish:</label> <input id="id_spanish" name="spanish" type="checkbox" checked="{{form.spanish.value}}"/>
                        </p>
                        <p class="clear">
                            <label for="id_others_languages">Others languages:</label> 
                            <input id="id_others_languages" maxlength="100" name="others_languages" type="text" value="{{form.others_languages.value}}"/>
                            {% include "form_errors.html" with errors=form.description.errors %}
                        </p>
                        <p class="fill centered">
                            <input type="submit" value="Submit" class="btn"/>
                        </p>
                </form>
            </div>
            <div class="span4">
                <p>El resto de info aquí</p>
            </div>
        </div>
    
    </div>

{% endblock %}

mentoring_manager/templates/person/home.html
{% extends "base.html" %}


{% block content %}

{{ person }}

{% endblock %}

mentoring_manager/templates/person/profile.html
{% extends "base.html" %}

{% block content %}

{{ person }}

{% endblock %}