mentoring_manager/entrepreneurs/urls.py
# Mentoring Manager is a web application to manage mentoring sessions between mentors and entrepreneurs.
# Copyright (C) 2013  Alvaro Hurtado Mochon (alvarohurtado84@gmail.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    
    url(r'create/$', 'entrepreneurs.views.create', name="entrepreneurs_create"),
    url(r'(?P<username>[a-zA-Z0-9\-\_]+)/$', 'entrepreneurs.views.profile', name="entrepreneurs_profile"),
    url(r'$', 'entrepreneurs.views.list', name="entrepreneurs_list"),

)

mentoring_manager/mentoring_manager/urls.py
# Mentoring Manager is a web application to manage mentoring sessions between mentors and entrepreneurs.
# Copyright (C) 2013  Alvaro Hurtado Mochon (alvarohurtado84@gmail.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

# ADMIN
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Home
    url(r'^$', 'mentoring_manager.views.home', name='home'),

    # People access (Profiles)
    url(r'^profile/', include('people.urls')),

    # Mentors
    url(r'^mentors/', include('mentors.urls')),

    # Entrepreneurs
    url(r'^entrepreneurs/', include('entrepreneurs.urls')),
    
    # Mentoring sessions
    url(r'^sessions/', include('mentoring_sessions.urls')),

    # ADMIN
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    
    # ACCOUNTS
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', name='logout'),
    
    # TOS
    url(
        r'^rules/$',
        TemplateView.as_view(template_name='rules.html'),
        name = 'rules',
        ),

    # MANIFESTO
    url(
        r'^manifesto/$',
        TemplateView.as_view(template_name='manifesto.html'),
        name = 'manifesto',
        ),
)

mentoring_manager/people/urls.py
# Mentoring Manager is a web application to manage mentoring sessions between mentors and entrepreneurs.
# Copyright (C) 2013  Alvaro Hurtado Mochon (alvarohurtado84@gmail.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    
    # Modify or update the user profile
    url(r'edit/$', 'people.views.edit', name="person_edit"),
    
    # Profile of any user
    url(r'(?P<username>[a-zA-Z0-9\-\_]+)/$', 'people.views.profile', name="person_profile"),
    
    # Profile of the logged user
    url(r'$', 'people.views.person_home', name="person_home"),
    
)

mentoring_manager/entrepreneurs/models.py
# Mentoring Manager is a web application to manage mentoring sessions between mentors and entrepreneurs.
# Copyright (C) 2013  Alvaro Hurtado Mochon (alvarohurtado84@gmail.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.db import models

from django.utils.translation import ugettext as _

from people.models import Person

STARTUP_STATE_CHOICES = [
    ["i", _("Idea")],
    ["bmd", _("Business model development")],
    ["mvpd", _("MVP Development")],
    ["bmv", _("Business model validation")],
    ["g", _("Growth")],
]

class Startup(models.Model):
    """Contains the startups data."""
    
    city = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    
    state = models.CharField(
        max_length=100,
        choices=STARTUP_STATE_CHOICES)
    
    name = models.CharField(max_length=100)
    avatar = models.ImageField(upload_to="avatars/startups",
                               blank=True, null=True)

    # What is the product or service you are building?
    about_product = models.TextField(blank=True, null=True)
    # Who is the customer, what problem are you solving?
    about_customer = models.TextField(blank=True, null=True)
    # Competitor and why people are going to prefer your product
    about_competitors = models.TextField(blank=True, null=True)
    
    # Website, video, twitter, presentation, anything else
    webs = models.TextField(blank=True, null=True)
    
    # Anything else you want to comment?
    more = models.TextField(blank=True, null=True)
  
    
    #
    # Private information for mentors
    #
    
    # When did you starto working on it?
    when_start = models.CharField(max_length=100, blank=True, null=True)
    legally_constituted = models.BooleanField()
    # How will you make money?
    business_model = models.TextField(blank=True, null=True)
    # Which is your commitment with the project?
    commitment = models.TextField(blank=True, null=True)
    # Resource (how many people in team, funds, already spent...)
    resources = models.TextField(blank=True, null=True)
    # Short, mid and long-term goals
    goals = models.TextField(blank=True, null=True)


class Entrepreneur(models.Model):
    """Contains the data of a Person related only with the entrepreneur role."""
    
    person = models.OneToOneField(Person)
    startup = models.ForeignKey(Startup, null=True)
    
    # Specific info for entrepreneurs here

mentoring_manager/entrepreneurs/forms.py
# Mentoring Manager is a web application to manage mentoring sessions between mentors and entrepreneurs.
# Copyright (C) 2013  Alvaro Hurtado Mochon (alvarohurtado84@gmail.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.forms import ModelForm

from entrepreneurs.models import Entrepreneur
from entrepreneurs.models import Startup


class EntrepreneurForm(ModelForm):
    class Meta:
        model = Entrepreneur
        
        
class StartupForm(ModelForm):
    class Meta:
        model = Startup

mentoring_manager/entrepreneurs/views.py
# Mentoring Manager is a web application to manage mentoring sessions between mentors and entrepreneurs.
# Copyright (C) 2013  Alvaro Hurtado Mochon (alvarohurtado84@gmail.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# Create your views here.

from django.utils.translation import ugettext as _
from django.shortcuts import render_to_response
from django.shortcuts import get_object_or_404

from django.http import Http404
from django.core.paginator import Paginator
from django.template import RequestContext

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from entrepreneurs.models import Entrepreneur
from people.models import Person

from entrepreneurs.forms import EntrepreneurForm
from entrepreneurs.forms import StartupForm
from people.forms import UserForm
from people.forms import PersonForm

from mentoring_manager.settings import ENTREPRENEUR_LIST_SIZE



def list(request):
    """Render a list of entrepreneurs."""
    
    entrepreneurs = Entrepreneur.objects.all()[:ENTREPRENEUR_LIST_SIZE]
    return render_to_response("entrepreneurs/list.html",
        {
            "entrepreneurs": entrepreneurs,
        },
        context_instance=RequestContext(request)
    )

def profile(request, username):
    """Render a detailed profile of the entrepreneur identified by username."""
    
    user = User.objects.get(username=username)
    
    if user.person.is_entrepreneur():
        entrepreneur = user.person.entrepreneur
    else:
        raise Http404
    
    return render_to_response("entrepreneurs/profile.html",
        {
            "entrepreneur": entrepreneur,
        },
        context_instance=RequestContext(request)
    )


def create(request):
    """Render a form to create an entrepreneur."""
    
    if request.method == "POST":
        
        user_form = UserForm(request.POST)
        startup_form = StartupForm(request.POST,  request.FILES)
        
        if user_form.is_valid() and startup_form.is_valid():
            user = user_form.save()
            startup = startup_form.save()
            
            person = Person()
            entrepreneur = Entrepreneur()
            
            person.user = user
            person.save()
            
            entrepreneur.person = person
            entrepreneur.startup = startup
            entrepreneur.save()
            
            msg = _("Your user and startup has been created successfully.")
            
            return render_to_response("entrepreneurs/create.html",
                {
                "msg": msg,
                "user": user,
                },
                context_instance=RequestContext(request)
            )

        else:
            return render_to_response("entrepreneurs/create.html",
                {
                    "user_form": user_form,
                    "startup_form": startup_form,
                },
                context_instance=RequestContext(request)
            )
        
    else:
        return render_to_response("entrepreneurs/create.html",
            {
                "user_form": UserForm(),
                "startup_form": StartupForm(),
            },
            context_instance=RequestContext(request)
        )
    

mentoring_manager/templates/entrepreneurs/create.html
{% extends "base.html" %}


{% block content %}

    <div class="container">   
        <div class="row">
            
            {% if user.is_authenticated and user.person.is_entrepreneur %}
                
                <div class="span12 centered">
                    <h1>Eyyyyy!!!! I have good news!...<br> </h1>
                
                    <img src="{{STATIC_URL}}images/icons/rocket-startup.png">

                    <h2 class="light">
                        You are already have your startup registered! ^_^ 
                    </h2>
                
                    <h3>Now.... where do you want to go?</h3>
                    <ul>
                        <li><a href="#" class="btn">To your profile</a></li>
                    </ul>
                    <div class="push"></div>
                </div>
            {% else %}
                {% if not user.is_authenticated %}
                    
                    <div class="span6 centered">
                        <h1>Join as an entrepreneur</h1>
                        <p>
                            
                        </p>
                        <img src="/static/images/icons/rocket-startup.png">
                    </div>
                    <div class="span6">
                        {{ msg }}
                        <h2>Register</h2>
                        <form class="register" action="{% url "entrepreneurs_create" %}" method="post"  enctype='multipart/form-data'>   
                            {% csrf_token %}
                            {{ user_form.as_p }}
                            <small class="login"><a href="{% url "login" %}">Do you already have an account? Sign in</a></small>
                            <input type="submit"/>
                        </form>
                    </div>
                    
                {% else %}
                    <div class="span12">
                        <h1 class="light">Register your Startup</h2>
                        <p>Lee las <a href="{% url "rules" %}">reglas de juego</a>, si estás conforme por favor rellena el siguiente formulario para poder empezar a solicitar sesiones.</p>
                    
                        <img src="{{STATIC_URL}}images/icons/rocket-startup.png" class="onright bg">
                    </div>

                    <div class="span12">
                        {{ msg }}
                        {{form.errors}}
                        {{ form.non_field_errors }}

                        <form class="register cols2" action="{% url "entrepreneurs_create" %}" method="post"  enctype='multipart/form-data'>   
                            {% csrf_token %}
                            <h2 class="light">Public data</h2>
                            <p>
                                <label for="id_name" class="fill">Name:(*)</label> 
                                <input id="id_name" maxlength="100" name="name" type="text" value="{{form.name.value}}"/>
                                {% include "form_errors.html" with errors=form.name.errors %}
                            </p>
                            <p>
                                <label for="id_city" class="fill">City:(*)</label> 
                                <input id="id_city" maxlength="100" name="city" type="text" value="{{form.city.value}}"/>
                                {% include "form_errors.html" with errors=form.city.errors %}
                            </p>
                            <p>
                                <label for="id_country" class="fill">Country:(*)</label> 
                                <input id="id_country" maxlength="100" name="country" type="text" value="{{form.country.value}}"/>
                                {% include "form_errors.html" with errors=form.country.errors %}
                            </p>
                            <p>
                                <label for="id_about_product">What is the product or service you are building?:</label> 
                                <textarea cols="40" id="id_about_product" name="about_product" rows="10">{{form.about_product.value}}</textarea>
                                {% include "form_errors.html" with errors=form.about_product.errors %}
                            </p>
                            <p>
                                <label for="id_webs">Website, video, twitter, presentation, anything else:</label> 
                                <textarea cols="40" id="id_webs" name="webs" rows="10">{{form.webs.value}}</textarea>
                                {% include "form_errors.html" with errors=form.webs.errors %}
                            </p>
                            <p>
                                <label for="id_more">Anything else you want to comment?:</label> 
                                <textarea cols="40" id="id_more" name="more" rows="10">{{form.more.value}}</textarea>
                                {% include "form_errors.html" with errors=form.more.errors %}
                            </p>
                            <p>
                                <label for="id_avatar">Logo:</label> 
                                <input id="id_avatar" name="avatar" type="file" />
                            </p>
                            
                            <hr>
                            <h2 class="clear light">Private data (for mentors)</h2>
                            <p>
                                <label for="id_state">Where are you? (state):(*)</label> 
                                <select id="id_state" name="state">
                                    <option value="" selected="selected">---------</option>
                                    <option value="i">Idea</option>
                                    <option value="bmd">Business model development</option>
                                    <option value="mvpd">MVP Development</option>
                                    <option value="bmv">Business model validation</option>
                                    <option value="g">Growth</option>
                                </select>
                                {% include "form_errors.html" with errors=form.id_state.errors %}
                            </p>
                            <p>
                                <label for="id_when_start">When did you start working on it?:</label> 
                                <input id="id_when_start" maxlength="100" name="when_start" type="text" value="{{form.when_start.value}}"/>
                                {% include "form_errors.html" with errors=form.when_start.errors %}
                            </p>
                            <p>
                                <label for="id_about_customer">Who is the customer, what problem are you solving?:</label> 
                                <textarea cols="40" id="id_about_customer" name="about_customer" rows="10">{{form.about_customer.value}}</textarea>
                                {% include "form_errors.html" with errors=form.about_customer.errors %}
                            </p>
                            <p>
                                <label for="id_about_competitors">Competitor and why people are going to prefer your product:</label> 
                                <textarea cols="40" id="id_about_competitors" name="about_competitors" rows="10">{{form.about_competitors.value}}</textarea>
                                {% include "form_errors.html" with errors=form.about_competitors.errors %}
                            </p>
                            <p>
                                <label for="id_business_model">How will you make money? (Business model):</label> 
                                <textarea cols="40" id="id_business_model" name="business_model" rows="10">{{form.business_model.value}}</textarea>
                                {% include "form_errors.html" with errors=form.business_model.errors %}
                            </p>
                            <p>
                                <label for="id_commitment">Which is your commitment with the project?:</label> 
                                <textarea cols="40" id="id_commitment" name="commitment" rows="10">{{form.commitment.value}}</textarea>
                                {% include "form_errors.html" with errors=form.commitment.errors %}
                            </p>
                            <p>
                                <label for="id_resources">Resource (how many people in team, funds, already spent...):</label>
                                <textarea cols="40" id="id_resources" name="resources" rows="10">{{form.resources.value}}</textarea>
                                {% include "form_errors.html" with errors=form.resources.errors %}
                            </p>
                            <p>
                                <label for="id_goals">Short, mid and long-term goals:</label> 
                                <textarea cols="40" id="id_goals" name="goals" rows="10">{{form.goals.value}}</textarea>
                                {% include "form_errors.html" with errors=form.goals.errors %}
                            </p>
                            <p>
                                <label for="id_legally_constituted">Are you legally constituted?:</label> 
                                <input id="id_legally_constituted" name="legally_constituted" type="checkbox" value="{{form.legally_constituted.value}}"/>
                                {% include "form_errors.html" with errors=form.legally_constituted.errors %}
                            </p>
                            <p>
                                <input id="game_rules" name="game_rules" type="checkbox" checked="{{form.game_rules.value}}" required="required"/> <label for="rules">I have read the <a href="{% url "rules" %}">Game Rules</a></label>
                            </p>
                            <input type="submit" class="clear"/>
                        </form>
                    </div>
                            
                    
                {% endif %}
            {% endif %}
        </div>
    </div>
    <div class="push"></div>

{% endblock %}

mentoring_manager/templates/entrepreneurs/list.html
{% extends "base.html" %}


{% block content %}

  <div class="container">
    <h1 class="onleft">Startups hosted in Mento
  </h1>
  {% if not user.person.is_entrepreneur %}
    <a href="{% url "entrepreneurs_create" %}" class="btn large shaded onright margin-top">Do you have an startup?</a>
  {% endif %}
                            
                            

    <ul class="inline-list clear">
      {% for e in entrepreneurs %}
          <li>
            <p>
              <a href="{% url "entrepreneurs_profile" e.person.user.username %}">
                <img src="{% if e.person.avatar %}{{STATIC_URL}}{{e.person.avatar}}{% else %}{{STATIC_URL}}images/icons/guest_startup.png{% endif %}"><br><br>
                {# Name:{{ e.person.user }}<br> #}
                Startup: {{ e.startup.name }}
              </a>
            </p>
          </li>
        {% empty %}
          <li>There are no mentors yet</li>
      {% endfor %}
    </ul>
</div>
{% endblock %}

mentoring_manager/templates/entrepreneurs/profile.html
{% extends "base.html" %}

{% block content %}


<div class="container">
  <div class="row">
      <div class="span12">
        <h1>Startup profile</h1>
        User=={{ entrepreneur.person.user }}<br>
        City=={{ entrepreneur.city }}<br>
        Country=={{ entrepreneur.country }}<br>
        State={{ entrepreneur.state }}<br>
        Name={{ entrepreneur.name }}<br>
        Choices={{ entrepreneur.choices }}<br>
        Avatar={{ entrepreneur.avatar }}<br>
        About_product={{ entrepreneur.about_product }}<br>
        Webs={{ entrepreneur.webs }}<br>
        More={{ entrepreneur.more }}<br>
         
  
        {{ entrepreneur }}
      </div>
  </div>
</div>

{% endblock %}